### ISSUE TITLE
Question on normal sampling

### ISSUE THREAD

**Issue by mks0601** [akashsengupta1997/STRAPS-3DHumanShapePose#2]
Hi,

Thanks for sharing your nice work!
I have a question about the normal sampling of the SMPL shape paramter.
In [here](https://github.com/akashsengupta1997/STRAPS-3DHumanShapePose/blob/f9b3a02ea4ca181c22584105f11b724d3de8c6e9/augmentation/smpl_augmentation.py#L23), you add `delta_betas` with `mean_shape`, but the `delta_betas` is already summed with `mean_shape` at the above line.
Is this a mistake or the `detla_betas` is calculated by adding `mean_shape`?

Also, could you let me know how did you get the `mean_shape` and `std_vector`?

**Comment by akashsengupta1997** [comment]
Hi,

Ah yes that is a bug that I forgot to fix in the code release, thanks for reminding me!

`mean_shape` is the same mean shape vector used by SPIN (https://github.com/nkolot/SPIN).

`std_vector` is basically a hyperparameter that can be set as desired, to control the variation in body shapes seen during training. I use `std_vector = [1.5, 1.5, ...., 1.5]` for most experiments. I also messed around with trying to get SMPL to generate and predict really muscular people, which was quite challenging and required std_vector = [1.5, 1.5, ...., 10, 10] - I guess since muscular people are very out-of-distribution compared to the SMPL training set! Anyway, the point is that `std_vector` can be set as desired depending on what you want to model.

**Comment by mks0601** [comment]
Awesome. Thanks!

**Comment by melih1996** [comment]
Hi @akashsengupta1997, is there any way you had followed to find the std_vector hyperparameter when you need to apply your model to the people in a specific distribution or a country, or you had only tried till you found it?
