### ISSUE TITLE
Different results when images of person taken at different distances

### ISSUE THREAD

**Issue by asimniazi63** [akashsengupta1997/STRAPS-3DHumanShapePose#6]
I have tried reconstructing same person based on various distances and results are hilarious. Would be appreciated if brief me about it and any solution about catering distances in your solution. 
Examples:

![rend_front_avg_distance](https://user-images.githubusercontent.com/15937296/103200206-939f6a00-490e-11eb-9105-0cfcfd7e7d70.jpg)
![rend_front_max_distance](https://user-images.githubusercontent.com/15937296/103200209-95692d80-490e-11eb-9c59-d8fa513eb586.jpg)
![rend_front_min_distance](https://user-images.githubusercontent.com/15937296/103200211-95692d80-490e-11eb-86cb-a2748bd851b1.jpg)
![rend_front_very_max_distance](https://user-images.githubusercontent.com/15937296/103200214-9601c400-490e-11eb-971a-2f56552c7758.jpg)
![rend_side_min_distance](https://user-images.githubusercontent.com/15937296/103200215-969a5a80-490e-11eb-9b0a-bad19b51763a.jpg)

**Comment by akashsengupta1997** [comment]
Hi,

Yes the system at the time this code was released was quite susceptible to changes in relative person size, because the training inputs were cropped to a bounding box around the synthetic silhouettes/joints (with a small random bbox scaling factor for augmentation). 

The standard way to deal with this is to also crop any test inputs around the detected silhouette/joints before 3D prediction to mimic the training data preprocessing, then un-crop after prediction, but it seems like I forgot to implement that in the code released here 😄. I'll get around to it when I've got some time. 

You could also try increasing the random bbox scaling range in data augmentation to train the network to be more robust, but the test-time solution makes more sense and will probably work better.
