### ISSUE TITLE
Using Male and Female Model

### ISSUE THREAD

**Issue by ujjawalcse** [akashsengupta1997/STRAPS-3DHumanShapePose#7]
Hi @akashsengupta1997 ,
Thanks for this great repository.
can you explain how to use smpl_male and smpl_female model for different genders?
Will it improve the shape obtained as result for diverse body shape?
Because many times it's generating inaccurate and fat body shape in A-pose images.
![20210204_150356_20210204_150720354](https://user-images.githubusercontent.com/32773256/107221818-26691380-6a3a-11eb-823e-742bc1907275.jpg)
![rend_20210204_150356_20210204_150720354](https://user-images.githubusercontent.com/32773256/107221720-00dc0a00-6a3a-11eb-80ef-3b1c9414458a.jpg)
![rend_20210204_150407_20210204_150720557](https://user-images.githubusercontent.com/32773256/107221725-033e6400-6a3a-11eb-9fca-e3cbdf9f5f82.jpg)

you can get a reference from these results.

**Comment by akashsengupta1997** [comment]
Hi,

Yes you can use  the gendered SMPL models by setting gender='male' or gender='female' in the SMPL model instantiation in run_train.py and run_predict.py. You will have to re-train the network - specifically train 2 new networks, one using only male synthetic data and the other using only female synthetic data, so you have a male predictor and a female predictor. Then at test-time you can just choose to use whichever network corresponds to the gender of the subject (of course if you don't know the gender of the subject you will have to classify it automatically somehow!). Using gendered SMPL does indeed help a lot with shape accuracy.

Another point is that the method here doesn't work well with baggy-ish clothing (since the silhouettes won't reflect the true body shape!) so that could also be problematic.

Good luck!

**Comment by akashsengupta1997** [comment]
oh and also you will need the SMPL male and female models from here (https://smpl.is.tue.mpg.de) and remove any chumpy objects from them using this (https://github.com/vchoutas/smplx/tree/master/tools)

**Comment by ujjawalcse** [comment]
Thanks @akashsengupta1997 for quick and explanatory reply.
Got it!

**Comment by akashsengupta1997** [comment]
You can use the provided training and validation pose parameters (since these are not affected by gender). Shape parameters are sampled randomly anyway during training. All you have to do to train with male/female synthetic data then is to add gender='male' or gender='female' to the smpl_model instantiation on line 109 of run_train.py.

**Comment by ujjawalcse** [comment]
Hi @akashsengupta1997,
I tried training from scratch on male body, training is too slow. So, I trained upto 30 epoch in 2 days on weekend.
But now i'm getting error while resuming the training from current epoch i.e 30.
`python run_train.py 

Device: cuda:0
GPU: 0

ResNet in channels: 18
ResNet layers: 18
IEF Num iters: 3

Batch size: 70
LR: 0.0001
Image width/height: 256

Losses on: ['verts', 'shape_params', 'pose_params', 'joints2D', 'joints3D']
Loss weights: {'verts': 1.0, 'joints2D': 0.1, 'pose_params': 0.1, 'shape_params': 0.1, 'joints3D': 1.0}

Metrics: ['pves', 'pves_sc', 'pves_pa', 'pve-ts', 'pve-ts_sc', 'mpjpes', 'mpjpes_sc', 'mpjpes_pa', 'shape_mses', 'pose_mses', 'joints2D_l2es']
Save val metrics: ['pves_pa', 'mpjpes_pa']

Train path: data/amass_up3d_3dpw_train.npz
Val path: data/up3d_3dpw_val.npz
Model save path: ./checkpoints/model_training/straps_model_checkpoint_exp001
Log save path: ./logs/straps_model_logs_exp001.pkl
Training examples found: 347962
Validation examples found: 11836

Regressor model Loaded.  11909789 trainable parameters.
WARNING: You are using a SMPL model, with only 10 shape coefficients.

SMPL augment params:
{'augment_shape': True, 'delta_betas_distribution': 'normal', 'delta_betas_std_vector': tensor([1.5000, 1.5000, 1.5000, 1.5000, 1.5000, 1.5000, 1.5000, 1.5000, 1.5000,
        1.5000], device='cuda:0'), 'delta_betas_range': [-3.0, 3.0]}
Cam augment params:
{'xy_std': 0.05, 'delta_z_range': [-5, 5]}
Crop input: True
BBox augment params
{'crop_input': True, 'mean_scale_factor': 1.2, 'delta_scale_range': [-0.2, 0.2], 'delta_centre_range': [-5, 5]}
Proxy rep augment params
{'remove_appendages': True, 'deviate_joints2D': True, 'deviate_verts2D': True, 'occlude_seg': True, 'remove_appendages_classes': [1, 2, 3, 4, 5, 6], 'remove_appendages_probabilities': [0.1, 0.1, 0.1, 0.1, 0.05, 0.05], 'delta_j2d_dev_range': [-8, 8], 'delta_j2d_hip_dev_range': [-8, 8], 'delta_verts2d_dev_range': [-0.01, 0.01], 'occlude_probability': 0.5, 'occlude_box_dim': 48}
Resuming from: ./checkpoints/model_training/straps_model_checkpoint_exp001_epoch30.tar

Training information loaded from checkpoint.
Current epoch: 31
Best epoch val metrics from last training run: {'pves_pa': 0.045244997332339984, 'mpjpes_pa': 0.03596175746229043}  - achieved in epoch: 28
Traceback (most recent call last):
  File "run_train.py", line 234, in <module>
    pin_memory=pin_memory)
  File "/home/ujjawal/my_work/Fashion/3d-body-measurements/STRAPS-3DHumanShapePose-master/train/train_synthetic_otf_rendering.py", line 93, in train_synthetic_otf_rendering
    current_epoch=current_epoch)
  File "/home/ujjawal/my_work/Fashion/3d-body-measurements/STRAPS-3DHumanShapePose-master/metrics/train_loss_and_metrics_tracker.py", line 41, in __init__
    self.history = self.load_history(log_path, current_epoch)
  File "/home/ujjawal/my_work/Fashion/3d-body-measurements/STRAPS-3DHumanShapePose-master/metrics/train_loss_and_metrics_tracker.py", line 87, in load_history
    str(current_epoch))
AssertionError: 0 elements in train_pve-ts_pa list when current epoch is 31`

Any idea how to solve this error.
And Anything we can do for fast training other than PC configuration.
